services:
  mariadb:
    container_name: ups-judge-db
    image: docker.io/mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=UpsJdg2025Root
      - MYSQL_USER=upsjudge
      - MYSQL_PASSWORD=UpsJdg2025App
      - MYSQL_DATABASE=upsjudge
    command: --max-connections=1000 --max-allowed-packet=512M --innodb_snapshot_isolation=OFF
    volumes:
      - mariadb_data:/var/lib/mysql

  domjudge:
    container_name: ups-judge-app
    image: astlimbark/ups-judge:latest
    restart: unless-stopped
    hostname: ups-judge
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - 80:80
    privileged: true
    environment:
      - CONTAINER_TIMEZONE=America/La_Paz
      - MYSQL_HOST=mariadb
      - MYSQL_USER=upsjudge
      - MYSQL_PASSWORD=UpsJdg2025App
      - MYSQL_DATABASE=upsjudge
      - MYSQL_ROOT_PASSWORD=UpsJdg2025Root
      - DJ_DB_INSTALL_BARE=1
    depends_on:
      - mariadb

  judgehost:
    container_name: ups-judge-judgehost
    image: domjudge/judgehost:latest
    restart: unless-stopped
    privileged: true
    hostname: judgedaemon
    environment:
      - CONTAINER_TIMEZONE=America/La_Paz
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=DpUR9xKqBAtvR75GDtrH00hwor2NPOsT
      - DOMSERVER_BASEURL=http://domjudge/
    depends_on:
      - domjudge

volumes:
  mariadb_data: